/* HyperCeiler glow.glsl adapter, AGPL-3.0. Upstream shader is shipped unchanged.
 * Copyright (C) 2023-2026 HyperCeiler Contributions. See guide-assets/AGPL-3.0.txt. */
window.GuideFlow=class {
  constructor(canvas,settled=false){this.canvas=canvas;this.time=settled?3:0;this.settled=settled;this.paused=false;this.dead=false;this.frame=0;this.direction=1;this.reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;this.visibility=()=>{this.canvas.parentElement.classList.toggle('flow-paused',document.hidden||this.paused||this.reduced);document.hidden?this.pause():this.resume()};document.addEventListener('visibilitychange',this.visibility);this.resize=()=>this.draw();this.observer=new ResizeObserver(this.resize);this.observer.observe(canvas);canvas.addEventListener('webglcontextlost',this.lost=e=>{e.preventDefault();this.fallback()});this.init();}
  async init(){try{const [shader,defaults]=await Promise.all([fetch('guide-assets/glow.glsl').then(r=>{if(!r.ok)throw Error('shader');return r.text()}),fetch('guide-assets/uniforms.json').then(r=>r.json())]);if(this.dead)return;const gl=this.canvas.getContext('webgl',{alpha:false,antialias:false,preserveDrawingBuffer:true});if(!gl)throw Error('WebGL unavailable');this.gl=gl;
    const compile=(type,source)=>{const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s};
    const program=gl.createProgram();gl.attachShader(program,compile(gl.VERTEX_SHADER,'attribute vec2 position;void main(){gl_Position=vec4(position,0.0,1.0);}'));gl.attachShader(program,compile(gl.FRAGMENT_SHADER,'precision highp float;\n'+shader.replace(/\b1 -/g,'1.0 -').replace('vec4 main(vec2 fragCoord)','vec4 renderGlow(vec2 fragCoord)')+'\nvoid main(){gl_FragColor=renderGlow(vec2(gl_FragCoord.x,uResolution.y-gl_FragCoord.y));}'));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(program));gl.useProgram(program);this.program=program;const buffer=gl.createBuffer();this.buffer=buffer;gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,1,1]),gl.STATIC_DRAW);const position=gl.getAttribLocation(program,'position');gl.enableVertexAttribArray(position);gl.vertexAttribPointer(position,2,gl.FLOAT,false,0,0);this.locations={};const uniform=(name)=>this.locations[name]??(this.locations[name]=gl.getUniformLocation(program,name));this.uniform=uniform;
    for(const [k,v] of Object.entries(defaults))Array.isArray(v)?gl.uniform3fv(uniform(k),v):gl.uniform1f(uniform(k),v);
    gl.uniform1f(uniform('uCircleYOffset'),0.12);gl.uniform1f(uniform('uShowCircle'),this.settled||this.reduced?0:1);this.canvas.dataset.renderer='webgl';if(this.reduced)this.time=3;this.draw();this.resume();
    }catch(e){this.canvas.dataset.error=String(e.message);this.fallback()}}
  draw(){if(!this.gl||!this.uniform||this.dead)return;const gl=this.gl,rect=this.canvas.getBoundingClientRect();if(!rect.width||!rect.height)return;const ratio=Math.min(devicePixelRatio||1,1.25,Math.sqrt(450000/(rect.width*rect.height)));const w=Math.max(1,Math.round(rect.width*ratio)),h=Math.max(1,Math.round(rect.height*ratio));if(this.canvas.width!==w||this.canvas.height!==h){this.canvas.width=w;this.canvas.height=h}gl.viewport(0,0,w,h);gl.uniform2f(this.uniform('uResolution'),w,h);gl.uniform1f(this.uniform('uTime'),this.time);gl.drawArrays(gl.TRIANGLE_STRIP,0,4)}
  resume(){if(this.dead||document.hidden||this.paused||this.reduced||!this.gl||this.frame)return;this.last=0;const tick=now=>{this.frame=0;if(this.dead||this.paused||document.hidden)return;if(this.last)this.time+=Math.min((now-this.last)/1000,.05)*this.direction;if(this.time>=120)this.direction=-1;if(this.time<=2&&this.direction<0)this.direction=1;this.last=now;this.draw();this.frame=requestAnimationFrame(tick)};this.frame=requestAnimationFrame(tick)}
  pause(){cancelAnimationFrame(this.frame);this.frame=0;this.last=0}
  freeze(){this.paused=true;this.pause();this.canvas.parentElement.classList.add('flow-paused')}
  thaw(){this.paused=false;this.canvas.parentElement.classList.remove('flow-paused');this.resume()}
  fallback(){this.pause();this.canvas.dataset.renderer='fallback';this.canvas.style.opacity='0';this.canvas.parentElement.classList.add('flow-fallback');if(this.reduced)this.canvas.parentElement.classList.add('flow-paused')}
  destroy(){this.dead=true;this.pause();this.observer.disconnect();document.removeEventListener('visibilitychange',this.visibility);this.canvas.removeEventListener('webglcontextlost',this.lost);if(this.gl){this.gl.deleteBuffer(this.buffer);this.gl.deleteProgram(this.program);this.gl.getExtension('WEBGL_lose_context')?.loseContext()}this.gl=null}
};
