document.addEventListener('DOMContentLoaded',()=>{
(function(){
const dialog=document.createElement('dialog');dialog.id='jwImportDialog';dialog.className='jw-dialog';dialog.innerHTML=`<button class="close" aria-label="关闭">×</button><div class="jw-heading"><img src="icon.svg" alt="" width="52" height="52"><p class="eyebrow">个人课表 · 保存在本机</p><h2>登录教务系统</h2><p class="muted">登录后解析个人课表。之后打开会自动读取已保存的课程。</p></div><section class="jw-step"><h3>1 · 选择校区作息</h3><label for="jwCampus">所在校区</label><select id="jwCampus"><option value="0">清远校区</option><option value="1">天河校区</option><option value="2">花都校区</option><option value="3">国际校区</option></select></section><section class="jw-step"><h3>2 · 登录并解析</h3><p class="muted">登录成功后即为首页个人课表。解析书签会读取本学期的全部教学周，只导出课程数据。</p><a class="primary jw-login" href="https://jw.gdcp.edu.cn/" target="_blank" rel="noopener noreferrer">登录教务系统 ↗</a><a class="jw-install" href="bookmark-install.html" target="_blank" rel="noopener">安装解析书签：电脑拖拽／手机复制 ↗</a><details class="jw-help"><summary>获取个人课表数据</summary><p>电脑：将下方链接拖到书签栏，登录教务首页后点击书签，将课程直接带回本网站核对。</p><a id="jwBookmark">解析个人课表（拖到书签栏）</a><button id="jwCopy">复制解析书签代码</button><p>手机可将代码保存为浏览器书签；浏览器不支持时，可从电脑导出后传至手机。也可在首页选“全部”，保存课表所在框架 HTML，再导入。</p></details></section><section class="jw-step"><h3>3 · 导入并核对</h3><label class="jw-file" for="jwFile">选择个人课表文件<input id="jwFile" type="file" accept=".json,.html,.htm"></label><p id="jwPreview" role="status" class="muted">支持 JSON 或 HTML，文件仅在本机解析。</p></section><button id="jwConfirm" class="primary" disabled>保存并查看课表</button><button id="jwLater" class="jw-later">稍后导入，先查看课表</button><p class="jw-footnote muted">保留自建课程。教务调整后重新导入；请保留 JSON，当前备份不包含独立个人导入数据。</p>`;
document.body.append(dialog);let pending=null,bookmark='';const status=()=>document.getElementById('jwStatus').textContent=window.GDCP_PERSONAL&&localStorage.getItem('timetable.jw.active')!=='false'?'正在使用个人教务课表 · '+window.GDCP_PERSONAL.courses.length+'条排课规则':'正在使用个人课表';
const rememberDismiss=()=>{};dialog.querySelector('.close').onclick=()=>{if(window.WebGuide?.active)window.WebGuide.back();else dialog.close()};dialog.addEventListener('cancel',rememberDismiss);document.getElementById('jwOpen').onclick=()=>{dialog.querySelector('#jwCampus').value=String(selectedCampus);dialog.showModal()};
dialog.querySelector('#jwLater').onclick=()=>{if(window.WebGuide?.active)window.WebGuide.complete();else dialog.close()};
fetch('jw-bookmark.json?v=3.3.1').then(r=>r.json()).then(code=>{bookmark=code;dialog.querySelector('#jwBookmark').href=code}).catch(()=>dialog.querySelector('#jwPreview').textContent='书签代码加载失败，请使用HTML导入');
dialog.querySelector('#jwCopy').onclick=async()=>{try{await navigator.clipboard.writeText(bookmark);notify('已复制，保存为浏览器书签的网址')}catch{notify('复制失败，可在电脑将链接拖到书签栏')}};
dialog.querySelector('#jwFile').onchange=async e=>{pending=null;dialog.querySelector('#jwConfirm').disabled=true;try{const file=e.target.files[0];if(!file)return;if(file.size>8*1024*1024)throw Error('文件超过8MB');const bytes=await file.arrayBuffer();let text=new TextDecoder().decode(bytes);if(/\.json$/i.test(file.name))pending=GDCPParser.validate(JSON.parse(text));else{if(/charset\s*=\s*["']?(gb2312|gbk|gb18030)/i.test(text))text=new TextDecoder('gb18030').decode(bytes);pending=GDCPParser.parse(new DOMParser().parseFromString(text.replace(/\s(?:src|srcset|href|style)\s*=\s*(?:"[^"]*"|'[^']*'|[^\s>]+)/gi,''),'text/html'))}dialog.querySelector('#jwPreview').textContent=`解析成功：${pending.courses.length}条排课规则，${pending.courses.reduce((n,c)=>n+c.weeks.length,0)}个课程时段。确认后替换已导入的个人课表。`;dialog.querySelector('#jwConfirm').disabled=false}catch(err){dialog.querySelector('#jwPreview').textContent='未导入：'+err.message}};
dialog.querySelector('#jwConfirm').onclick=()=>{if(!pending)return;const campus=Number(dialog.querySelector('#jwCampus').value);const updates={'timetable.jw.personal.v1':JSON.stringify(pending),'timetable.jw.active':'true',[PREFS_KEY]:JSON.stringify({version:1,className:className(),campus}),'timetable.onboarding.v1':'done'};const before={};try{for(const key of Object.keys(updates))before[key]=localStorage.getItem(key);for(const [key,value] of Object.entries(updates))localStorage.setItem(key,value)}catch{for(const [key,value] of Object.entries(before))try{value===null?localStorage.removeItem(key):localStorage.setItem(key,value)}catch{}dialog.querySelector('#jwPreview').textContent='保存失败，请允许浏览器本地存储后重试。';notify('保存失败，请允许浏览器本地存储');return}window.GDCP_PERSONAL=pending;selectedCampus=campus;setupCompleted=true;refreshAll();status();if(window.WebGuide?.active)window.WebGuide.complete();else dialog.close();notify('个人课表已保存至本机')};
document.getElementById('jwUseClass').onclick=()=>{try{localStorage.setItem('timetable.jw.active','false');refreshAll();status();notify('已切回个人课表')}catch{notify('本地存储不可用')}};status();
window.PersonalImportUI={dialog,accept(data){try{pending=GDCPParser.validate(data);dialog.querySelector('#jwPreview').textContent=`已接收 ${pending.courses.length} 条排课规则、${pending.courses.reduce((n,c)=>n+c.weeks.length,0)} 个时段。请核对校区后保存。`;dialog.querySelector('#jwConfirm').disabled=false}catch(e){pending=null;dialog.querySelector('#jwConfirm').disabled=true;dialog.querySelector('#jwPreview').textContent='未导入：'+e.message}},open(){dialog.querySelector('#jwCampus').value=String(selectedCampus);dialog.showModal();dialog.dispatchEvent(new Event('campusrefresh'))}};
const select=dialog.querySelector('#jwCampus');select.hidden=true;
const campus=document.createElement('div');campus.className='jw-campus-buttons';campus.setAttribute('role','radiogroup');campus.setAttribute('aria-label','选择校区作息');
for(const option of select.options){const button=document.createElement('button');button.type='button';button.textContent=option.text;button.dataset.value=option.value;button.setAttribute('role','radio');button.onclick=()=>{select.value=option.value;refreshCampus()};campus.append(button)}
select.after(campus);campus.onkeydown=e=>{if(!['ArrowDown','ArrowUp','ArrowLeft','ArrowRight'].includes(e.key))return;e.preventDefault();const buttons=[...campus.children],i=buttons.indexOf(document.activeElement),next=(i+(['ArrowDown','ArrowRight'].includes(e.key)?1:3))%4;buttons[next].click();buttons[next].focus()};
function refreshCampus(){for(const b of campus.children){b.setAttribute('aria-checked',String(b.dataset.value===select.value));b.classList.toggle('selected',b.dataset.value===select.value)}}
dialog.addEventListener('campusrefresh',refreshCampus);refreshCampus();
document.getElementById('jwOpen').onclick=()=>window.PersonalImportUI.open();
})();

});