(function(){
const dialog=document.createElement('dialog');dialog.innerHTML='<button class="close" aria-label="关闭">×</button><h2>个人教务课表</h2><p>先登录学校教务系统，打开个人课表，选择2026—2027第一学期、全部周次。本站不能读取其他网站的登录状态。</p><p><a href="https://jw.gdcp.edu.cn/" target="_blank" rel="noopener noreferrer">打开教务系统 ↗</a></p><p>电脑：将下方链接拖至书签栏，进入个人课表后点击书签，导出仅包含课程的 JSON。手机：可将解析代码保存为浏览器书签；不支持此方式时，在电脑导出后传至手机。</p><a id="jwBookmark">解析个人课表（拖到书签栏）</a><button id="jwCopy">复制书签代码</button><p>也可保存完整个人课表页面为 HTML 后导入。HTML 在本机解析，不上传、不执行其中的脚本。</p><label>导入 JSON 或 HTML <input id="jwFile" type="file" accept=".json,.html,.htm"></label><p id="jwPreview" role="status"></p><button id="jwConfirm" disabled>确认使用个人课表</button><p>保留当前校区作息及自建课程；个人课表按实际选课显示，不再过滤班级分组。每次教务调整后重新导入。此导入数据另行保存，原有备份格式不包含它，请保留导出的 JSON。</p>';
document.body.append(dialog);let pending=null,bookmark='';const status=()=>document.getElementById('jwStatus').textContent=window.GDCP_PERSONAL&&localStorage.getItem('timetable.jw.active')!=='false'?'正在使用个人教务课表 · '+window.GDCP_PERSONAL.courses.length+'条排课规则':'正在使用班级课表';
dialog.querySelector('.close').onclick=()=>dialog.close();document.getElementById('jwOpen').onclick=()=>dialog.showModal();
fetch('jw-bookmark.json').then(r=>r.json()).then(code=>{bookmark=code;dialog.querySelector('#jwBookmark').href=code}).catch(()=>dialog.querySelector('#jwPreview').textContent='书签代码加载失败，请使用HTML导入');
dialog.querySelector('#jwCopy').onclick=async()=>{try{await navigator.clipboard.writeText(bookmark);notify('已复制，保存为浏览器书签的网址')}catch{notify('复制失败，可在电脑将链接拖到书签栏')}};
dialog.querySelector('#jwFile').onchange=async e=>{pending=null;dialog.querySelector('#jwConfirm').disabled=true;try{const file=e.target.files[0];if(!file)return;if(file.size>8*1024*1024)throw Error('文件超过8MB');const bytes=await file.arrayBuffer();let text=new TextDecoder().decode(bytes);if(/\.json$/i.test(file.name))pending=GDCPParser.validate(JSON.parse(text));else{if(/charset\s*=\s*["']?(gb2312|gbk|gb18030)/i.test(text))text=new TextDecoder('gb18030').decode(bytes);pending=GDCPParser.parse(new DOMParser().parseFromString(text.replace(/\s(?:src|srcset|href|style)\s*=\s*(?:"[^"]*"|'[^']*'|[^\s>]+)/gi,''),'text/html'))}dialog.querySelector('#jwPreview').textContent=`解析成功：${pending.courses.length}条排课规则，${pending.courses.reduce((n,c)=>n+c.weeks.length,0)}个课程时段。确认后替换已导入的个人课表。`;dialog.querySelector('#jwConfirm').disabled=false}catch(err){dialog.querySelector('#jwPreview').textContent='未导入：'+err.message}};
dialog.querySelector('#jwConfirm').onclick=()=>{if(!pending)return;try{localStorage.setItem('timetable.jw.personal.v1',JSON.stringify(pending));localStorage.setItem('timetable.jw.active','true');window.GDCP_PERSONAL=pending;localStorage.setItem(PREFS_KEY,JSON.stringify({version:1,className:className(),campus:selectedCampus}));setupCompleted=true;refreshAll();status();dialog.close();notify('个人课表已保存至本机')}catch{notify('保存失败，请允许浏览器本地存储')}};
document.getElementById('jwUseClass').onclick=()=>{try{localStorage.setItem('timetable.jw.active','false');refreshAll();status();notify('已切回班级课表')}catch{notify('本地存储不可用')}};status();
})();
