'use strict';
const STATE_KEY='timetable.personalization.v1';
let userState={groups:{},custom:{}}, mode='auto', activePage=0;
const reduceMotion=matchMedia('(prefers-reduced-motion: reduce)');
try{const saved=JSON.parse(localStorage.getItem(STATE_KEY)||'null');if(saved&&saved.groups&&saved.custom)userState=saved;mode=localStorage.getItem('timetable.view')||'auto'}catch{}
if(!['auto','day','week'].includes(mode))mode='auto';
function notify(text){$('toast').textContent=text;$('toast').hidden=false;clearTimeout(notify.timer);notify.timer=setTimeout(()=>$('toast').hidden=true,3600)}
function persist(next=userState){try{localStorage.setItem(STATE_KEY,JSON.stringify(next));userState=next;return true}catch{notify('无法保存到浏览器，请允许本地存储后再试。');return false}}
function className(index=selectedClass){return catalog.classes[index].name}
function groupKey(name){if(name.includes('体育'))return '体育课';const at=name.indexOf('分组');return at<0?'':name.slice(0,at).replace(/[（(\s]+$/,'')}
function groupOption(c){return c.name+'｜教师：'+c.teacher}
function groupLabel(option){const [name,teacher]=option.split('｜教师：');const match=name.match(/[（(]分组(\d+)[（(](.+?)[）)][）)]/);if(match)return `${match[2]} · 第${match[1]}组 · 教师：${teacher}`;const project=catalog.teacherProjects?.[teacher];return (project&&name.includes('体育')?project+'（据其他课表）':name.includes('体育')?'大学体育 · 项目未标注':name)+' · 教师：'+teacher}
function courseLabel(c){const project=catalog.teacherProjects?.[c.teacher];return c.name.includes('体育')&&!c.name.includes('分组')&&project?`大学体育（${project}）`:c.name}
function groupsFor(index){const groups={};for(const c of decodeClass(index)){const key=groupKey(c.name);if(key)(groups[key]??=[]).includes(groupOption(c))||groups[key].push(groupOption(c))}return groups}
function selectedGroups(){return userState.groups[className()]||{}}
function rebuildCourses(){const choices=selectedGroups();COURSES=(window.GDCP_PERSONAL&&localStorage.getItem("timetable.jw.active")!=="false"?window.GDCP_PERSONAL.courses:decodeClass(selectedClass)).filter(c=>{const key=groupKey(c.name),value=choices[key]||'*';return (window.GDCP_PERSONAL&&localStorage.getItem('timetable.jw.active')!=='false')||!key||value==='*'||value===groupOption(c)});for(const [i,c] of (userState.custom[className()]||[]).entries())COURSES.push({name:c.name,teacher:c.teacher,position:c.room,day:c.day,sections:Array.from({length:c.last-c.first+1},(_,n)=>c.first+n),weeks:c.weeks,customIndex:i});names=[...new Set(COURSES.map(c=>c.name))]}
const originalCreate=createCourse;
createCourse=function(c,compact=false){const button=originalCreate(c,compact);button.querySelector('strong').textContent=courseLabel(c);return button};
const originalDetail=showDetail;
showDetail=function(c){originalDetail(c);$('detailName').textContent=courseLabel(c);$('sportsNote').textContent='体育课按所选分组或教师显示，具体以个人教务课表为准。';$('deleteCourse')?.remove();if(c.customIndex!==undefined){const b=document.createElement('button');b.id='deleteCourse';b.textContent='删除自建课程';b.onclick=()=>{if(!confirm('删除这门自建课程？'))return;const next=structuredClone(userState);next.custom[className()].splice(c.customIndex,1);if(persist(next)){ $('detail').close();refreshAll();renderCustomList();notify('课程已删除')}};$('detail').append(b)}};
const originalSettings=settings;
settings=function(){originalSettings();$('classTitle').textContent=className();const lines=['课程来自你的个人教务课表或本机自建课程，体育课以实际个人选课为准。'];lines.push('本版本无内置课表，课程仅在本机保存。');$('scheduleNotes').replaceChildren();const h=document.createElement('h3');h.textContent='课表说明';$('scheduleNotes').append(h);for(const line of lines){const p=document.createElement('p');p.textContent=line;$('scheduleNotes').append(p)}let g=$('selectedGroupsText');if(!g){const dt=document.createElement('dt');dt.textContent='分组';g=document.createElement('dd');g.id='selectedGroupsText';document.querySelector('.selection-values').append(dt,g)}g.textContent=Object.entries(selectedGroups()).map(([key,v])=>key+' · '+(v==='*'?'保留全部（待确认）':v==='none'?'不显示':groupLabel(v))).join('；')||'无分组选课'};
function refreshAll(){rebuildCourses();settings();renderToday();render()}
let draftGroups={};
const originalUpdateDraft=updateDraft;
updateDraft=function(){originalUpdateDraft();const groups=draftClass>=0?groupsFor(draftClass):{};$('setupConfirm').disabled=draftClass<0||draftCampus<0||Object.keys(groups).some(k=>!draftGroups[k])};
function renderGroupChoices(){const host=$('groupOptions');host.replaceChildren();if(draftClass<0)return;const groups=groupsFor(draftClass);if(!Object.keys(groups).length)return;const h=document.createElement('h3');h.textContent='3 · 体育课与分组选课';host.append(h);for(const [category,options] of Object.entries(groups)){const fs=document.createElement('fieldset');fs.className='group-choice';const legend=document.createElement('legend');legend.textContent=category;fs.append(legend);for(const value of ['*','none',...options]){const label=document.createElement('label'),radio=document.createElement('input'),span=document.createElement('span');radio.type='radio';radio.name='group:'+category;radio.value=value;radio.checked=draftGroups[category]===value;span.textContent=value==='*'?'保留全部（待确认）':value==='none'?'不显示此类课程':groupLabel(value);radio.onchange=()=>{draftGroups[category]=value;updateDraft()};label.append(radio,span);fs.append(label)}host.append(fs)}updateDraft()}
const originalClassOptions=classOptions;
classOptions=function(){originalClassOptions();for(const radio of $('classOptions').querySelectorAll('input')){const prev=radio.onchange;radio.onchange=()=>{prev();draftGroups={...(userState.groups[className(draftClass)]||{})};renderGroupChoices();updateDraft()}}};
const originalOpenSetup=openSetup;
openSetup=function(){originalOpenSetup();draftGroups={...(draftClass>=0?userState.groups[className(draftClass)]||{}:{})};renderGroupChoices();updateDraft()};
confirmSetup=function(){if($('setupConfirm').disabled)return;const next=structuredClone(userState);next.groups[className(draftClass)]={...draftGroups};try{const previousState=localStorage.getItem(STATE_KEY);localStorage.setItem(STATE_KEY,JSON.stringify(next));try{localStorage.setItem(PREFS_KEY,JSON.stringify({version:1,className:className(draftClass),campus:draftCampus}))}catch(e){if(previousState===null)localStorage.removeItem(STATE_KEY);else localStorage.setItem(STATE_KEY,previousState);throw e}}catch{notify('设置无法保存，请允许浏览器本地存储后重试。');return}userState=next;selectedClass=draftClass;selectedCampus=draftCampus;setupCompleted=true;refreshAll();$('classPicker').close();notify('课表设置已保存')};
$('classTrigger').onclick=()=>openSetup();$('setupConfirm').onclick=()=>confirmSetup();$('classSearch').oninput=()=>classOptions();
// Timetable rows support arbitrary custom sections, overlaps and responsive day/week modes.
render=function(){const courses=forWeek(selectedWeek);$('weekTitle').textContent=`第 ${String(selectedWeek).padStart(2,'0')} 周`;$('weekTrigger').textContent=`第 ${selectedWeek} 周 ▾`;$('week').value=selectedWeek;$('range').textContent=`${fmt(dateFor(selectedWeek,1))} — ${fmt(dateFor(selectedWeek,7))} · ${courses.length} 个课程时段`;$('prev').disabled=selectedWeek===1;$('next').disabled=selectedWeek===20;$('trainingNotice').hidden=!personal()||![3,4].includes(selectedWeek);$('semesterNotice').hidden=currentWeek>=1&&currentWeek<=20;$('semesterNotice').textContent='当前日期不在本学期内，可以浏览全部教学周。';$('empty').hidden=courses.length>0;$('grid').replaceChildren();$('days').replaceChildren();const corner=document.createElement('div');corner.className='day-head';corner.textContent='节次 / 时间';$('grid').append(corner);for(let d=1;d<=7;d++){const date=dateFor(selectedWeek,d),head=document.createElement('div');head.className='day-head'+(+date===todayStamp?' is-today':'');head.append(`星期${dayNames[d-1]}`);const small=document.createElement('small');small.textContent=fmt(date);head.append(small);$('grid').append(head);const b=document.createElement('button');b.type='button';b.className=d===selectedDay?'active':'';b.setAttribute('aria-pressed',d===selectedDay);b.setAttribute('aria-label',`星期${dayNames[d-1]} ${fmt(date)}`);b.append(dayNames[d-1]);const n=document.createElement('small');n.textContent=date.getUTCDate();b.append(n);b.onclick=()=>changeSchedule(()=>selectedDay=d);$('days').append(b)}for(let s=1;s<=12;s+=2){const label=document.createElement('div');label.className='time';label.append(`${s}–${s+1}节`);const sm=document.createElement('small');sm.textContent=s===3?'10:10–11:35\n部分区域\n10:30–11:55':`${TIMER.sections[s-1].startTime}\n${TIMER.sections[s].endTime}`;label.append(sm);$('grid').append(label);for(let d=1;d<=7;d++){const cell=document.createElement('div');cell.className='cell';courses.filter(c=>c.day===d&&Math.ceil(c.sections[0]/2)*2-1===s).forEach(c=>cell.append(createCourse(c)));$('grid').append(cell)}}$('daily').replaceChildren();const daily=courses.filter(c=>c.day===selectedDay).sort((a,b)=>a.sections[0]-b.sections[0]);for(const c of daily){const row=document.createElement('div');row.className='daily-row';const time=document.createElement('div');time.className='time';time.append(`${c.sections[0]}–${c.sections.at(-1)}节`);const small=document.createElement('small');small.textContent=clock(c);time.append(small);row.append(time,createCourse(c));$('daily').append(row)}if(!daily.length){const p=document.createElement('p');p.className='daily-empty';p.textContent='这一天没有排课。';$('daily').append(p)}applyMode()};
function applyMode(){const resolved=mode==='auto'?(innerWidth>=900?'week':'day'):mode;$('timetablePage').dataset.view=resolved;document.querySelectorAll('button[data-view]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.view===mode))}
// Outgoing content is preserved until the crossfade finishes. Queue only the latest selection.
let scheduleAnimation=null;
function changeSchedule(change){
 const content=$('courseContent'),oldHeight=content.getBoundingClientRect().height;
 change();render();scheduleAnimation?.cancel();if(reduceMotion.matches)return;
 const height=content.getBoundingClientRect().height;
 scheduleAnimation=content.animate([{opacity:.3,transform:'translateX(14px)'},{opacity:1,transform:'translateX(0)'}],{duration:500,delay:height>=oldHeight?180:0,fill:'backwards',easing:'ease-out'});
}
$('prev').onclick=()=>changeSchedule(()=>selectedWeek=Math.max(1,selectedWeek-1));$('next').onclick=()=>changeSchedule(()=>selectedWeek=Math.min(20,selectedWeek+1));$('current').onclick=()=>changeSchedule(()=>{selectedWeek=Math.max(1,Math.min(20,currentWeek));selectedDay=(initial.getDay()+6)%7+1});$('week').onchange=e=>changeSchedule(()=>selectedWeek=Number(e.target.value));
$('weekTrigger').onclick=()=>{const host=$('weekOptions');host.replaceChildren();for(let w=1;w<=20;w++){const b=document.createElement('button');b.type='button';b.textContent=w;b.className=w===selectedWeek?'active':'';b.setAttribute('aria-pressed',w===selectedWeek);b.setAttribute('aria-label',`第${w}周`);b.onclick=()=>{changeSchedule(()=>selectedWeek=w);$('weekPicker').close()};host.append(b)}$('weekPicker').showModal()};
for(const b of document.querySelectorAll('button[data-view]'))b.onclick=()=>changeSchedule(()=>{mode=b.dataset.view;try{localStorage.setItem('timetable.view',mode)}catch{}});
addEventListener('resize',()=>{applyMode();positionCapsule(activePage);updateTitle()});
const scrollPositions=[0,0],pageAnimations=[];
function positionCapsule(fraction){const step=($('dockTabs').clientWidth-8)/2;$('capsule').style.setProperty('--capsule-x',`${step*fraction}px`)}
let navigationRevision=0;
async function switchPage(target){
 if(target===activePage||document.querySelector('dialog[open]'))return;
 const revision=++navigationRevision,old=activePage,oldScroll=scrollY;
 scrollPositions[old]=oldScroll;activePage=target;
 const outgoing=$(old?'aboutPage':'timetablePage'),incoming=$(target?'aboutPage':'timetablePage');
 const interrupted=pageAnimations.some(a=>a.playState==='running');
 const oldTransform=getComputedStyle(outgoing).transform,newTransform=getComputedStyle(incoming).transform;
 for(const a of pageAnimations)a.cancel();pageAnimations.length=0;
 for(const p of [incoming,outgoing]){p.style.position='';p.style.top='';p.style.left='';p.style.right=''}
 incoming.hidden=false;incoming.inert=false;incoming.removeAttribute('aria-hidden');
 outgoing.inert=true;outgoing.setAttribute('aria-hidden','true');
 // Keep the outgoing viewport unchanged while restoring the destination's own scroll.
 const destination=Math.min(scrollPositions[target],Math.max(0,incoming.scrollHeight-innerHeight));
 $('pages').style.minHeight=Math.max(incoming.scrollHeight,destination+innerHeight)+'px';
 outgoing.style.position='absolute';outgoing.style.top=(destination-oldScroll)+'px';outgoing.style.left='0';outgoing.style.right='0';
 positionCapsule(target);for(let i=0;i<2;i++)$('tab'+i).setAttribute('aria-selected',i===target);
 scrollTo({top:destination,behavior:'instant'});updateTitle(true);
 if(!reduceMotion.matches){
  const direction=target>old?1:-1,distance=document.documentElement.clientWidth;
  pageAnimations.push(incoming.animate([{transform:interrupted&&newTransform!=='none'?newTransform:`translateX(${direction*distance}px)`},{transform:'translateX(0)'}],{duration:420,easing:'cubic-bezier(.2,0,.2,1)'}),outgoing.animate([{transform:interrupted&&oldTransform!=='none'?oldTransform:'translateX(0)'},{transform:`translateX(${-direction*distance}px)`}],{duration:420,easing:'cubic-bezier(.2,0,.2,1)'}));
  await Promise.allSettled(pageAnimations.map(a=>a.finished));
 }
 if(revision!==navigationRevision)return;
 outgoing.hidden=true;for(const p of [incoming,outgoing]){p.style.position='';p.style.top='';p.style.left='';p.style.right=''}
 $('pages').style.minHeight='';updateTitle();
}
for(let i=0;i<2;i++)$('tab'+i).onclick=()=>switchPage(i);
$('dockTabs').addEventListener('keydown',e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();const target=e.key==='ArrowRight'?1:0;switchPage(target);$('tab'+target).focus()}});
let drag=null;
$('dockTabs').addEventListener('pointerdown',e=>{if(e.button!==0)return;drag={id:e.pointerId,x:e.clientX,start:activePage,moved:false};$('capsule').style.setProperty('--capsule-scale','.9')});
addEventListener('pointermove',e=>{if(!drag||e.pointerId!==drag.id)return;const dx=e.clientX-drag.x;if(Math.abs(dx)>5){drag.moved=true;$('dockTabs').classList.add('dragging');drag.value=Math.max(0,Math.min(1,drag.start+dx/(($('dockTabs').clientWidth-8)/2)));positionCapsule(drag.value)}});
function endDrag(e,cancel=false){if(!drag||drag.id!==e.pointerId)return;const current=drag;drag=null;$('dockTabs').classList.remove('dragging');$('capsule').style.setProperty('--capsule-scale','1');if(current.moved&&!cancel){switchPage(current.value>=.5?1:0);positionCapsule(activePage)}else positionCapsule(activePage);if(current.moved){suppressDockClick=true;setTimeout(()=>suppressDockClick=false,0)}}
let suppressDockClick=false;$('dockTabs').addEventListener('click',e=>{if(suppressDockClick){e.stopImmediatePropagation();e.preventDefault()}},true);addEventListener('pointerup',e=>endDrag(e));addEventListener('pointercancel',e=>endDrag(e,true));
let swipe=null;$('pages').addEventListener('pointerdown',e=>{if(e.pointerType!=='touch'||e.target.closest('button,input,select,a,.grid-scroll,dialog'))return;swipe={x:e.clientX,y:e.clientY,id:e.pointerId}});$('pages').addEventListener('pointerup',e=>{if(!swipe||swipe.id!==e.pointerId)return;const dx=e.clientX-swipe.x,dy=e.clientY-swipe.y;swipe=null;if(Math.abs(dx)>56&&Math.abs(dx)>Math.abs(dy)*1.35)switchPage(dx<0?1:0)});$('pages').addEventListener('pointercancel',()=>swipe=null);
let titleAnimation=null;
function updateTitle(changed=false){
 const title=$('topTitle');title.textContent=activePage?'关于':'个人课表';
 const blurAlpha=Math.max(0,Math.min(1,scrollY/40));$('topEdge').style.setProperty('--scroll-blur',String(blurAlpha));$('topEdge').style.visibility=blurAlpha>0?'visible':'hidden';const alpha=Math.max(0,Math.min(1,(scrollY-48)/56));title.style.opacity=String(alpha);title.style.filter=`blur(${8*(1-alpha)}px)`;title.style.transform=`scale(${.92+.08*alpha})`;
 if(changed){titleAnimation?.cancel();if(!reduceMotion.matches&&alpha>0)titleAnimation=title.animate([{filter:'blur(6px)',transform:'scale(.94)'},{filter:`blur(${8*(1-alpha)}px)`,transform:`scale(${.92+.08*alpha})`}],{duration:360,easing:'ease-out'})}
}
// Adapted from AndrewPrifer/progressive-blur LinearBlur (MIT, license included).
function mountProgressiveBlur(){
 const host=$('topEdge');host.replaceChildren();const steps=8,strength=72,step=100/steps,base=Math.pow(strength/.5,1/(steps-1));
 for(let i=0;i<steps;i++){
  const band=document.createElement('div');band.className='blur-band';
  const mask=i===0?`linear-gradient(to bottom,#000 0%,transparent ${step}%)`:i===1?`linear-gradient(to bottom,#000 0%,#000 ${step}%,transparent ${step*2}%)`:`linear-gradient(to bottom,transparent ${(i-2)*step}%,#000 ${(i-1)*step}%,#000 ${i*step}%,transparent ${(i+1)*step}%)`;
  const filter=`blur(${(.5*Math.pow(base,steps-i-1)).toFixed(3)}px)`;
  band.style.maskImage=mask;band.style.webkitMaskImage=mask;band.style.backdropFilter=filter;band.style.webkitBackdropFilter=filter;band.style.zIndex=String(i+1);host.append(band);
 }
}
mountProgressiveBlur();
let ticking=false;addEventListener('scroll',()=>{if(!ticking){ticking=true;requestAnimationFrame(()=>{updateTitle();ticking=false})}},{passive:true});
// Dialogs use the same close animation for page back, Escape and browser back.
let routeBusy=false;
async function openRoute(id){if($(id).open||routeBusy)return;const d=$(id),origin=$('addOpen').getBoundingClientRect();d._origin=origin;d.showModal();document.body.classList.add('route-open');history.pushState({timetableRoute:id},'');d.dataset.history='true';const first=d.querySelector('.route-back');first.focus({preventScroll:true});if(!reduceMotion.matches){const r=d.getBoundingClientRect();const frames=id==='addPage'?[{transform:`translate(${origin.left-r.left}px,${origin.top-r.top}px) scale(${origin.width/r.width},${origin.height/r.height})`,transformOrigin:'top left',borderRadius:'56px',background:'#3482ff',boxShadow:'0 12px 32px #0004'},{transform:'translate(0,0) scale(1)',transformOrigin:'top left',borderRadius:innerWidth<900?'28px 28px 0 0':'28px 0 0 28px',background:getComputedStyle(document.body).backgroundColor,boxShadow:'-24px 0 70px #0004'}]:[{transform:'translateX(100%)'},{transform:'translateX(0)'}];const a=d.animate(frames,{duration:id==='addPage'?440:560,easing:'cubic-bezier(.2,0,.2,1)'});d.querySelector('form')?.animate([{opacity:0},{opacity:1}],{duration:220,delay:220,fill:'backwards'});await a.finished.catch(()=>{})}}
async function closeRoute(d,fromHistory=false){if(routeBusy||!d.open)return;routeBusy=true;document.activeElement?.blur();if(!reduceMotion.matches){const origin=d._origin||$('addOpen').getBoundingClientRect(),r=d.getBoundingClientRect();const frames=d.id==='addPage'?[{transform:'translate(0,0) scale(1)',transformOrigin:'top left',borderRadius:'28px'},{transform:`translate(${origin.left-r.left}px,${origin.top-r.top}px) scale(${origin.width/r.width},${origin.height/r.height})`,transformOrigin:'top left',borderRadius:'56px',opacity:.2}]:[{transform:'translateX(0)'},{transform:'translateX(100%)'}];await d.animate(frames,{duration:480,easing:'cubic-bezier(.2,0,.2,1)'}).finished.catch(()=>{})}d.close();document.body.classList.remove('route-open');routeBusy=false;if(!fromHistory&&d.dataset.history==='true'){d.dataset.history='false';history.back()}(d.id==='addPage'?$('addOpen'):$('settingsOpen')).focus({preventScroll:true})}
addEventListener('popstate',()=>{const d=document.querySelector('.route-dialog[open]');if(d){d.dataset.history='false';closeRoute(d,true)}});
for(const d of document.querySelectorAll('.route-dialog')){d.querySelector('.route-back').onclick=()=>closeRoute(d);d.addEventListener('cancel',e=>{e.preventDefault();closeRoute(d)})}
$('settingsOpen').onclick=()=>{renderCustomList();openRoute('settingsPage')};$('addOpen').onclick=()=>{$('courseError').textContent='';openRoute('addPage')};
function parseWeeks(text){const weeks=new Set();for(const part of text.trim().replace(/[，、]/g,',').replace(/[—–]/g,'-').split(',')){if(!/^\s*\d+(\s*-\s*\d+)?\s*$/.test(part))throw Error('周次格式示例：5-18 或 5,7,9-12；范围1至20。');const [a,b=a]=part.split('-').map(Number);if(a<1||b>20||a>b)throw Error('教学周范围为1至20。');for(let w=a;w<=b;w++)weeks.add(w)}return [...weeks].sort((a,b)=>a-b)}
function validateCourse(c){for(const k of ['name','teacher','room'])if(typeof c[k]!=='string'||c[k].length>500)throw Error('课程文字格式无效。');if(!c.name.trim()||!Number.isInteger(c.day)||c.day<1||c.day>7||!Number.isInteger(c.first)||!Number.isInteger(c.last)||c.first<1||c.last>12||c.first>c.last)throw Error('请检查课程名称、星期和节次。');if(!Array.isArray(c.weeks)||!c.weeks.length||c.weeks.length>20||new Set(c.weeks).size!==c.weeks.length||c.weeks.some(w=>!Number.isInteger(w)||w<1||w>20))throw Error('课程周次无效。')}
const form=$('courseForm');for(const [name,total] of [['day',7],['first',12],['last',12]])for(let n=1;n<=total;n++){const o=document.createElement('option');o.value=n;o.textContent=name==='day'?'星期'+dayNames[n-1]:`第${n}节`;form.elements[name].append(o)}form.elements.last.value=2;
form.onsubmit=async e=>{e.preventDefault();try{const f=new FormData(form),course={name:f.get('name').trim(),teacher:f.get('teacher').trim(),room:f.get('room').trim(),day:Number(f.get('day')),first:Number(f.get('first')),last:Number(f.get('last')),weeks:parseWeeks(f.get('weeks'))};validateCourse(course);const next=structuredClone(userState);(next.custom[className()]??=[]).push(course);if(!persist(next))return;refreshAll();await closeRoute($('addPage'));form.reset();form.elements.last.value=2;notify('课程已添加')}catch(e){$('courseError').textContent=e.message}};
function renderCustomList(){const host=$('customList');host.replaceChildren();const courses=userState.custom[className()]||[];if(!courses.length){host.textContent='当前课表暂无自建课程，点击底栏蓝色加号添加。';return}courses.forEach((c,i)=>{const row=document.createElement('div');row.className='custom-row';const info=document.createElement('div'),title=document.createElement('strong'),sub=document.createElement('p'),del=document.createElement('button');title.textContent=c.name;sub.className='muted';sub.textContent=`星期${dayNames[c.day-1]} · ${c.first}–${c.last}节 · ${weekRanges(c.weeks)}`;del.textContent='删除';del.setAttribute('aria-label','删除'+c.name);del.onclick=()=>{if(!confirm('删除这门自建课程？'))return;const next=structuredClone(userState);next.custom[className()].splice(i,1);if(persist(next)){refreshAll();renderCustomList()}};info.append(title,sub);row.append(info,del);host.append(row)})}
function validateCatalog(data){
 if(!data||!Array.isArray(data.strings)||!Array.isArray(data.classes)||!data.classes.length||data.classes.length>2000||data.strings.length>100000)throw Error('课表数据无效');
 if(data.strings.some(s=>typeof s!=='string'||s.length>500))throw Error('课表文字无效');
 const names=new Set();let count=0;
 for(const c of data.classes){if(typeof c.name!=='string'||!c.name||c.name.length>500||names.has(c.name)||!Array.isArray(c.courses))throw Error('课表无效');names.add(c.name);
 for(const r of c.courses){if(++count>100000||!Array.isArray(r)||r.length!==6||!r.every(Number.isInteger)||r.slice(0,3).some(n=>n<0||n>=data.strings.length)||r[3]<1||r[3]>7||r[4]<1||r[4]>11||r[5]<1||r[5]>1048575)throw Error('课程数据无效')}}
 if(data.teacherProjects&&Object.values(data.teacherProjects).some(v=>typeof v!=='string'||v.length>500))throw Error('体育项目无效');return data;
}
function backupData(){return {format:'gdcp-timetable-backup',version:1,semester:'2026-2027-1',settings:{className:className(),campus:selectedCampus},groups:userState.groups,custom:userState.custom,catalog}}
function validateBackup(root){if(!root||root.format!=='gdcp-timetable-backup'||root.version!==1||root.semester!=='2026-2027-1')throw Error('备份格式或学期不匹配。');const incoming=root.catalog?validateCatalog(root.catalog):catalog;const known=n=>incoming.classes.some(c=>c.name===n);if(!root.settings||!known(root.settings.className)||!Number.isInteger(root.settings.campus)||root.settings.campus<0||root.settings.campus>3)throw Error('备份课表或校区无效。');for(const key of ['groups','custom'])if(!root[key]||typeof root[key]!=='object'||Array.isArray(root[key]))throw Error('备份内容无效。');for(const [name,g] of Object.entries(root.groups)){if(!known(name)||!g||typeof g!=='object'||Array.isArray(g))throw Error('备份分组无效。');for(const [key,value] of Object.entries(g))if(key.length>200||typeof value!=='string'||value.length>500)throw Error('备份分组选项无效。')}let total=0;for(const [name,courses] of Object.entries(root.custom)){if(!known(name)||!Array.isArray(courses))throw Error('备份课程无效。');total+=courses.length;if(total>10000)throw Error('自建课程数量过多。');courses.forEach(validateCourse)}return root}
$('exportBackup').onclick=()=>{const blob=new Blob([JSON.stringify(backupData(),null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='个人课表-备份.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);notify('备份已导出')};$('importBackup').onclick=()=>$('backupFile').click();
$('backupFile').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;try{if(file.size>4*1024*1024)throw Error('备份文件超过4MB。');const root=validateBackup(JSON.parse(await file.text()));if(!confirm(`导入「${root.settings.className}」的备份？当前设置及自建课程将被替换。`))return;const nextCatalog=root.catalog||catalog,next={groups:root.groups,custom:root.custom};const keys=[CATALOG_KEY,STATE_KEY,PREFS_KEY],previous=keys.map(k=>localStorage.getItem(k));try{localStorage.setItem(CATALOG_KEY,JSON.stringify(nextCatalog));localStorage.setItem(STATE_KEY,JSON.stringify(next));localStorage.setItem(PREFS_KEY,JSON.stringify({version:1,...root.settings}))}catch(e){keys.forEach((k,i)=>{if(previous[i]===null)localStorage.removeItem(k);else localStorage.setItem(k,previous[i])});throw e}catalog=nextCatalog;window.SCHOOL_DATA=catalog;userState=next;selectedClass=catalog.classes.findIndex(c=>c.name===root.settings.className);selectedCampus=root.settings.campus;setupCompleted=true;refreshAll();renderCustomList();notify('备份已恢复');if(Object.entries(groupsFor(selectedClass)).some(([k,options])=>!['*','none',...options].includes(selectedGroups()[k]))){hasLegacyChoice=true;setupCompleted=false;openSetup()}}catch(e){notify('导入失败：'+e.message)}};
// Existing visitors keep class/campus; new group settings require one explicit confirmation.
try{validateBackup(backupData())}catch{userState={groups:{},custom:{}};notify('本地自建课程或分组数据无效，请重新设置或导入备份。')}
const required=groupsFor(selectedClass);if(Object.entries(required).some(([k,options])=>!['*','none',...options].includes(selectedGroups()[k]))){hasLegacyChoice=setupCompleted||hasLegacyChoice;setupCompleted=false}
refreshAll();positionCapsule(activePage);updateTitle();if(!setupCompleted){setupCompleted=true}
