(function(root){
'use strict';
const START=Date.parse('2026-08-31T00:00:00+08:00'),DAY=86400000;
const campusNames=['清远校区','天河校区','花都校区','国际校区'];
const starts=['08:30','09:15','10:10','10:55','14:15','15:00','15:55','16:35','18:05','18:45','19:40','20:20'];
const ends=['09:10','09:55','10:50','11:35','14:55','15:40','16:35','17:15','18:45','19:25','20:20','21:00'];
function decode(data,index){return data.classes[index].courses.map(r=>({name:data.strings[r[0]],teacher:data.strings[r[1]],room:data.strings[r[2]],day:r[3],first:r[4],last:r[4]+1,weeks:Array.from({length:20},(_,i)=>i+1).filter(w=>r[5]&(1<<(w-1)))}))}
function category(name){if(name.includes('体育'))return '体育课';const at=name.indexOf('分组');return at<0?'':name.slice(0,at).replace(/[（(\s]+$/,'')}
const option=c=>c.name+'｜教师：'+c.teacher;
function groups(data,index){const result={};for(const c of decode(data,index)){const k=category(c.name);if(k){result[k]??=[];if(!result[k].includes(option(c)))result[k].push(option(c))}}return result}
function label(data,c){const project=data.teacherProjects?.[c.teacher];return c.name.includes('体育')&&!c.name.includes('分组')&&project?`大学体育（${project}，据其他课表）`:c.name}
function delayed(room,campus){if(campus===0)return /融新|融创|12#|13#|操场|运动场|体育馆/.test(room);if(campus===1)return /2号楼|2-|运动场|操场/.test(room);if(campus===2)return /10号楼|15号楼|16号楼|10-|15-|16-|运动场|操场/.test(room);return !/教学楼|运动场|操场/.test(room)}
function clock(c,campus,end=false){const n=end?c.last:c.first;if(delayed(c.room,campus)){if(n===3)return end?'11:10':'10:30';if(n===4)return end?'11:55':'11:15'}return(end?ends:starts)[n-1]}
function validateCourse(c){if(!c||typeof c.name!=='string'||!c.name.trim()||c.name.length>500||typeof c.teacher!=='string'||c.teacher.length>500||typeof c.room!=='string'||c.room.length>500||!Number.isInteger(c.day)||c.day<1||c.day>7||!Number.isInteger(c.first)||!Number.isInteger(c.last)||c.first<1||c.last>12||c.first>c.last||!Array.isArray(c.weeks)||!c.weeks.length||c.weeks.length>20||new Set(c.weeks).size!==c.weeks.length||c.weeks.some(w=>!Number.isInteger(w)||w<1||w>20))throw Error('自建课程格式无效。')}
function validateBackup(data,b){if(!b||b.format!=='gdcp-timetable-backup'||b.version!==1||b.semester!==data.semester)throw Error('备份格式或学期不匹配。');if(!b.settings||!data.classes.some(c=>c.name===b.settings.className)||!Number.isInteger(b.settings.campus)||b.settings.campus<0||b.settings.campus>3)throw Error('课表或校区无效。');let total=0;for(const k of ['groups','custom'])if(!b[k]||typeof b[k]!=='object'||Array.isArray(b[k]))throw Error('备份内容无效。');for(const [n,cs]of Object.entries(b.custom)){if(!data.classes.some(c=>c.name===n)||!Array.isArray(cs)||(total+=cs.length)>10000)throw Error('自建课程内容无效。');cs.forEach(validateCourse)}for(const [n,g]of Object.entries(b.groups)){if(!data.classes.some(c=>c.name===n)||!g||typeof g!=='object'||Array.isArray(g)||Object.entries(g).some(([k,v])=>k.length>200||typeof v!=='string'||v.length>500))throw Error('分组内容无效。')}return b}
const dateText=ms=>new Date(ms+8*3600000).toISOString().slice(0,10);
function eventText(e){return `${e.date} · ${e.start.slice(11,16)}–${e.end.slice(11,16)} · ${e.first}–${e.last}节\n${e.name}\n教师：${e.teacher||'未标注'}\n地点：${e.room||'未标注'}`}
function nextText(events,now){const current=events.filter(e=>Date.parse(e.start)<=now&&now<Date.parse(e.end));const future=events.filter(e=>Date.parse(e.start)>now);const earliest=future[0]?.start;const next=future.filter(e=>e.start===earliest);return(current.length?'正在上课\n'+current.map(eventText).join('\n\n')+'\n\n':'')+(next.length?'下一节课\n'+next.map(eventText).join('\n\n'):'本学期没有尚未开始的课程。')}
function build(data,profile){const index=data.classes.findIndex(c=>c.name===profile.className);if(index<0||!Number.isInteger(profile.campus)||profile.campus<0||profile.campus>3)throw Error('请选择有效课表和校区。');const choices=profile.groups||{},available=groups(data,index);for(const [k,opts]of Object.entries(available))if(!['*','none',...opts].includes(choices[k]))throw Error('请确认体育课及其他分组选课。');const custom=profile.custom||[];if(custom.length>10000)throw Error('自建课程过多。');custom.forEach(validateCourse);const rules=decode(data,index).filter(c=>{const k=category(c.name);return !k||choices[k]==='*'||choices[k]===option(c)}).concat(custom);const events=[];for(const c of rules)for(const w of c.weeks){const date=dateText(START+((w-1)*7+c.day-1)*DAY);events.push({...c,name:label(data,c),week:w,date,start:`${date}T${clock(c,profile.campus)}:00+08:00`,end:`${date}T${clock(c,profile.campus,true)}:00+08:00`})}events.sort((a,b)=>Date.parse(a.start)-Date.parse(b.start)||a.name.localeCompare(b.name));
const heading=`个人课表 · ${profile.className} · ${campusNames[profile.campus]}`,footer='最新调整以教务系统为准。体育分组以个人选课为准。';const daily={},weekly={};for(let d=0;d<140;d++){const date=dateText(START+d*DAY),week=Math.floor(d/7)+1,rows=events.filter(e=>e.date===date);daily[d]=`${heading}\n${date} · 星期${'一二三四五六日'[d%7]} · 第${week}周\n\n${rows.length?rows.map(eventText).join('\n\n'):'这一天没有排课。'}${data.classes[index].personal&&[3,4].includes(week)?'\n本周安排军训（含入学教育），具体时间以学校通知为准。':''}\n\n${footer}`;const weekEvents=events.filter(e=>e.week===week);weekly[d]=`${heading}\n第${week}周 · ${dateText(START+(week-1)*7*DAY)}—${dateText(START+((week-1)*7+6)*DAY)}\n\n`+Array.from({length:7},(_,i)=>{const day=dateText(START+((week-1)*7+i)*DAY),rows=weekEvents.filter(e=>e.date===day);return`星期${'一二三四五六日'[i]} · ${day}\n${rows.length?rows.map(eventText).join('\n\n'):'无排课'}`}).join('\n\n')+(data.classes[index].personal&&[3,4].includes(week)?'\n\n军训（含入学教育）：具体时间以学校通知为准。':'')+`\n\n${footer}`}
const boundaries=[...new Set([START,...events.flatMap(e=>[Date.parse(e.start),Date.parse(e.end)]),START+140*DAY])].sort((a,b)=>a-b);const nextIntervals=boundaries.slice(1).map((b,i)=>({before:(b-START)/1000,text:`${heading}\n\n${nextText(events,boundaries[i])}\n\n${footer}`}));
return{format:'gdcp-shortcuts-timetable',version:1,semester:data.semester,timezone:'Asia/Shanghai',checked:data.checked,semesterStart:'2026-08-31T00:00:00+08:00',semesterEnd:'2027-01-18T00:00:00+08:00',profile:{className:profile.className,campus:profile.campus,groups:choices},events,daily,weekly,nextIntervals,outside:`${heading}\n当前日期不在2026—2027第一学期内（2026-08-31至2027-01-17）。请重新配置或在网页版浏览全部教学周。`}}
function query(pkg,mode,now){if(mode==='tomorrow')now+=DAY;const d=Math.floor((now-START)/DAY);if(d<0||d>=140)return pkg.outside;if(mode==='next')return pkg.nextIntervals.find(x=>x.before>(now-START)/1000)?.text||pkg.outside;return(mode==='week'?pkg.weekly:pkg.daily)[d]}
const escape=s=>String(s).replace(/\\/g,'\\\\').replace(/\r?\n/g,'\\n').replace(/;/g,'\\;').replace(/,/g,'\\,');
function fold(line){const chunks=[];let out='',bytes=0;for(const c of line){const size=new TextEncoder().encode(c).length;if(bytes+size>75){chunks.push(out);out=' ';bytes=1}out+=c;bytes+=size}chunks.push(out);return chunks.join('\r\n')}
function hash(s){let h=2166136261;for(const c of s)h=Math.imul(h^c.codePointAt(0),16777619);return(h>>>0).toString(16)}
function ics(pkg){const stamp=isoUTC(Date.now());const lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//GDCP Class Timetable//Shortcuts v1//ZH','CALSCALE:GREGORIAN','X-WR-CALNAME:'+escape('个人课表 · '+pkg.profile.className),'X-WR-TIMEZONE:Asia/Shanghai'];const seen=new Map();for(const e of pkg.events){const identity=JSON.stringify([pkg.profile.className,e.start,e.end,e.name,e.teacher,e.room]),n=seen.get(identity)||0;seen.set(identity,n+1);lines.push('BEGIN:VEVENT',`UID:${hash(identity)}-${n}@gdcp-class-timetable`,`DTSTAMP:${stamp}`,`DTSTART:${isoUTC(Date.parse(e.start))}`,`DTEND:${isoUTC(Date.parse(e.end))}`,`SUMMARY:${escape(e.name)}`,`LOCATION:${escape(e.room)}`,`DESCRIPTION:${escape(`教师：${e.teacher}\n课表：${pkg.profile.className}\n第${e.week}周 · ${e.first}–${e.last}节\n数据核对：${pkg.checked}\n最新调整以教务系统为准`)}`,'BEGIN:VALARM','TRIGGER:-PT10M','ACTION:DISPLAY','DESCRIPTION:课程即将开始','END:VALARM','END:VEVENT')}lines.push('END:VCALENDAR');return lines.map(fold).join('\r\n')+'\r\n'}
function isoUTC(ms){return new Date(ms).toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z$/,'Z')}
root.GDCPShortcuts={START,DAY,campusNames,decode,groups,option,category,clock,build,query,ics,validateBackup};if(typeof module!=='undefined')module.exports=root.GDCPShortcuts;
})(typeof window!=='undefined'?window:globalThis);
