'use strict';
const S=GDCPShortcuts,$=id=>document.getElementById(id),KEY='gdcp.shortcuts.profile.v1';
let data=SCHOOL_DATA;try{const saved=localStorage.getItem('timetable.catalog.v1');if(saved)data=JSON.parse(saved)}catch{}
let config={className:'',campus:null,groups:{},custom:[]},groupMap={},customMap={},pkg=null;
try{const saved=JSON.parse(localStorage.getItem(KEY)||'null');if(saved){config=saved.profile;groupMap=saved.groups||{};customMap=saved.custom||{}}else{const p=JSON.parse(localStorage.getItem('timetable.preferences.v1')||'null'),u=JSON.parse(localStorage.getItem('timetable.personalization.v1')||'null');if(p){config={className:p.className,campus:p.campus,groups:u?.groups?.[p.className]||{},custom:u?.custom?.[p.className]||[]};groupMap=u?.groups||{};customMap=u?.custom||{}}}}catch{$('status').textContent='缓存无法读取，请重新配置。'}
function save(){try{localStorage.setItem(KEY,JSON.stringify({profile:config,groups:groupMap,custom:customMap}))}catch{$('status').textContent='浏览器不允许保存设置；本次仍可下载文件。'}}
function classes(){const select=$('class');select.replaceChildren(new Option('请选择班级',''));const text=$('search').value.trim().toLowerCase();data.classes.forEach((c,i)=>{if(c.name.toLowerCase().includes(text)||c.name===config.className)select.append(new Option(c.name,String(i)))});const index=data.classes.findIndex(c=>c.name===config.className);select.value=index<0?'':String(index)}
function renderGroups(){const host=$('groups');host.replaceChildren();const index=data.classes.findIndex(c=>c.name===config.className);if(index<0)return;for(const [key,options]of Object.entries(S.groups(data,index))){const label=document.createElement('label');label.textContent=key;const select=document.createElement('select');select.setAttribute('aria-label',key);select.append(new Option('请选择分组',''),new Option('保留全部（待确认）','*'),new Option('不显示此类课程','none'));for(const value of options){const [name,teacher]=value.split('｜教师：');const project=data.teacherProjects?.[teacher];select.append(new Option(name+(project&&!name.includes('分组')?' · '+project+'（据其他班级）':'')+' · 教师：'+teacher,value))}select.value=config.groups[key]||'';select.onchange=()=>{config.groups[key]=select.value;groupMap[config.className]={...config.groups};save();refresh()};host.append(label,select)}}
function refresh(){pkg=null;$('status').textContent='';try{pkg=S.build(data,config)}catch(e){$('count').textContent=e.message}$('json').disabled=$('ics').disabled=!pkg;$('custom').textContent=`自建课程：${config.custom?.length||0} 条；可通过网页／安卓备份读取。`;if(pkg){$('count').textContent=`已生成 ${pkg.events.length} 个课程时段 · ${config.className} · ${S.campusNames[config.campus]}`;$('preview').textContent=S.query(pkg,$('previewMode').value,Date.now())}else $('preview').textContent='完成班级、校区和分组设置后显示预览。'}
$('search').oninput=classes;$('class').onchange=()=>{config.className=data.classes[Number($('class').value)]?.name||'';if($('class').value==='')config.className='';config.groups={...(groupMap[config.className]||{})};config.custom=customMap[config.className]||[];renderGroups();save();refresh()};$('campus').value=config.campus===null?'':String(config.campus);$('campus').onchange=()=>{config.campus=$('campus').value===''?null:Number($('campus').value);save();refresh()};$('previewMode').onchange=refresh;
$('backup').onchange=async e=>{const f=e.target.files[0];e.target.value='';if(!f)return;try{if(f.size>4*1024*1024)throw Error('备份超过4MB。');const raw=JSON.parse(await f.text());const b=S.validateBackup(raw.catalog||data,raw);if(!confirm('读取备份将替换此页面的配置，是否继续？'))return;if(b.catalog)data=b.catalog;groupMap=b.groups;customMap=b.custom;config={...b.settings,groups:{...(groupMap[b.settings.className]||{})},custom:customMap[b.settings.className]||[]};classes();renderGroups();$('campus').value=String(config.campus);save();refresh()}catch(e){$('status').textContent='读取失败：'+e.message}};
function download(text,name,type){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000)}
$('json').onclick=()=>{if(pkg)download(JSON.stringify(pkg),'GDCP-Class-Timetable.json','application/json')};$('ics').onclick=()=>{if(pkg)download(S.ics(pkg),'GDCP-Class-Timetable.ics','text/calendar;charset=utf-8')};classes();renderGroups();refresh();
