package cn.gdcp.timetable;
import android.app.*;
import android.os.Bundle;
import android.webkit.*;
import android.net.Uri;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.nio.charset.StandardCharsets;
public final class JwImportActivity extends Activity {
 private WebView web;private TextView status;private Button parse;private boolean busy=false;
 private boolean allowed(String url){try{Uri u=Uri.parse(url);return "https".equals(u.getScheme())&&"jw.gdcp.edu.cn".equals(u.getHost());}catch(Exception e){return false;}}
 @Override public void onCreate(Bundle state){super.onCreate(state);getWindow().setFlags(WindowManager.LayoutParams.FLAG_SECURE,WindowManager.LayoutParams.FLAG_SECURE);LinearLayout layout=new LinearLayout(this);layout.setOrientation(LinearLayout.VERTICAL);setContentView(layout);layout.setOnApplyWindowInsetsListener((v,insets)->{v.setPadding(insets.getSystemWindowInsetLeft(),insets.getSystemWindowInsetTop(),insets.getSystemWindowInsetRight(),insets.getSystemWindowInsetBottom());return insets;});layout.requestApplyInsets();
  status=new TextView(this);status.setPadding(20,16,20,16);status.setText("登录学校教务系统后打开首页个人课表，选择2026—2027第一学期、全部周次。解析只保存课程，不保存账号密码。返回可取消。");layout.addView(status);
  LinearLayout controls=new LinearLayout(this);layout.addView(controls);Button personal=new Button(this);personal.setText("打开首页个人课表");controls.addView(personal,new LinearLayout.LayoutParams(0,-2,1));parse=new Button(this);parse.setText("解析并预览");controls.addView(parse,new LinearLayout.LayoutParams(0,-2,1));
  web=new WebView(this);layout.addView(web,new LinearLayout.LayoutParams(-1,0,1));WebSettings settings=web.getSettings();settings.setJavaScriptEnabled(true);settings.setDomStorageEnabled(true);settings.setAllowFileAccess(false);settings.setAllowContentAccess(false);settings.setMixedContentMode(WebSettings.MIXED_CONTENT_NEVER_ALLOW);settings.setSaveFormData(false);CookieManager.getInstance().setAcceptThirdPartyCookies(web,false);
  web.setWebViewClient(new WebViewClient(){@Override public boolean shouldOverrideUrlLoading(WebView v,WebResourceRequest r){return !allowed(r.getUrl().toString());}@Override public void onReceivedSslError(WebView v,android.webkit.SslErrorHandler h,android.net.http.SslError e){h.cancel();status.setText("教务系统证书验证失败，请稍后重试。");}@Override public void onPageFinished(WebView v,String url){status.setText("首页个人课表加载后点“解析并预览”。个人课表以实际选课为准。");}});
  personal.setOnClickListener(v->web.loadUrl("https://jw.gdcp.edu.cn/jsxsd/framework/xsMainV.htmlx"));parse.setOnClickListener(v->extract());web.loadUrl("https://jw.gdcp.edu.cn/");
 }
 private void extract(){if(busy||!allowed(web.getUrl()))return;busy=true;parse.setEnabled(false);try{java.io.InputStream input=getAssets().open("jw-parser.js");java.io.ByteArrayOutputStream output=new java.io.ByteArrayOutputStream();byte[] buffer=new byte[8192];int count;while((count=input.read(buffer))!=-1)output.write(buffer,0,count);input.close();String parser=new String(output.toByteArray(),StandardCharsets.UTF_8);web.evaluateJavascript("(function(){"+parser+";window.__gdcpImportResult=null;GDCPParser.collect(document).then(data=>{window.__gdcpImportResult=JSON.stringify({ok:true,data:data})}).catch(e=>{window.__gdcpImportResult=JSON.stringify({ok:false,error:e.message})});return true})()",ignored->poll(0));}catch(Exception e){busy=false;parse.setEnabled(true);status.setText("解析器读取失败。");}}
 private void poll(int attempt){if(isFinishing()||isDestroyed())return;web.evaluateJavascript("window.__gdcpImportResult||null",raw->{if(raw==null||raw.equals("null")){if(attempt>=100){busy=false;parse.setEnabled(true);status.setText("读取超时，请确认已登录且首页课表加载完成，再重试。");}else new android.os.Handler(android.os.Looper.getMainLooper()).postDelayed(()->poll(attempt+1),150);return;}busy=false;parse.setEnabled(true);try{String text=new JSONArray("["+raw+"]").getString(0);JSONObject result=new JSONObject(text);if(!result.optBoolean("ok"))throw new JSONException(result.optString("error","解析失败"));JSONObject clean=PersonalImport.validate(result.getJSONObject("data").toString());JSONArray rows=clean.getJSONArray("courses");int slots=0;for(int i=0;i<rows.length();i++)slots+=rows.getJSONObject(i).getJSONArray("weeks").length();new AlertDialog.Builder(this).setTitle("确认导入个人课表").setMessage(rows.length()+"条排课规则，"+slots+"个课程时段。保留当前校区作息和自建课程，替换已导入的个人课表。原有备份不包含教务导入，请保留个人课表JSON。").setNegativeButton("取消",null).setPositiveButton("保存到本机",(d,w)->{try{PersonalImport.save(this,clean.toString());finish();}catch(Exception e){status.setText("保存失败，请重新解析。");}}).show();}catch(Exception e){status.setText("未导入："+e.getMessage());}});}
 @Override public void onBackPressed(){if(web.canGoBack())web.goBack();else super.onBackPressed();}
 @Override protected void onDestroy(){if(web!=null){web.stopLoading();web.clearCache(true);web.clearHistory();web.destroy();android.webkit.WebStorage.getInstance().deleteAllData();}CookieManager.getInstance().removeAllCookies(null);CookieManager.getInstance().flush();super.onDestroy();}
}
